config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  #resources :specialties
  #devise_for :users
  devise_for :users #, :controllers => { registrations: 'registrations' }
  resources :users_admin, :controller => 'users'


  #devise_for :users


  resources :tests
  resources :users
  root 'main#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/user.rb
class User < ApplicationRecord
  has_one :roles
  has_many :admins
  has_many :patients

  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :username, :presence => true, :uniqueness => true
  validates :role_id, :presence => true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  #
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit]

  def index
    if current_user.role_id == 1
      @users = User.all.order(updated_at: :desc)
    else
      render :show
    end
  end

  def show

  end

  def new
    @user = User.new
  end


  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(account_update_params)
      redirect_to users_admin_index_url, notice: "User updated successfully !!!"
    else
      render :edit
    end
  end

  def create
    @user = User.new(sign_up_params)
    if @user.save
      redirect_to user_url, notice: "User created successfully !!!"
    else
      render :new
    end
  end

  private
  def set_user
    #begin
    @user = User.find(params[:id])
    @role = current_user.role_id
  end

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :dob, :gender,
                                 :contact, :username, :province, :city_village, :address_line_1, :role_id)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password,:dob,
                                 :gender, :province, :city_village, :address_line_1, :contact, :username, :role_id)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li , class="notice" ><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name , "First Name" %><br />
    <%= f.text_field :first_name, autocomplete: "on" %>
  </div>

  <div class="field">
    <%= f.label :last_name, "Last Name" %><br />
    <%= f.text_field :last_name, autocomplete: "on" %>
  </div>

  <div class="field">
    <%= f.label :email, "Email" %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :username, "Username" %><br />
    <%= f.text_field :username, autocomplete: "on" %>
  </div>

  <div class="field">
    <%= f.label :password, "Password" %>
    <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :role_id, "Role" %>
    <%= f.select :role_id, options_for_select(Role.all.map {|p| [ p.description, p.id ]}, "Select Role"),:prompt => "Select Role",:required => true  %>
  </div>


  <div class="field">
    <%= f.label :gender, "Gender" %>
    <%= f.select :gender, ['Please Select', 'Male', 'Female', 'Others'],
                 :selected => 'Select One' %>
  </div>

  <div class="field">
    <%= f.label :Date_of_Birth, "Date Of Birth" %><br />
    <%= f.date_select :dob %>
  </div>

  <div class="field">
    <%= f.label :contact, "Contact Number" %><br />
    <%= f.text_field :contact, autocomplete: "on" %>
  </div>

  <div class="field">
    <%= f.label :province, "Province" %><br />
    <%= f.text_field :province, autocomplete: "on" %>
  </div>

  <div class="field">
    <%= f.label :city_village, "City or Village" %><br />
    <%= f.text_field :city_village, autocomplete: "on" %>
  </div>

  <div class="field">
    <%= f.label :address_line_1, "Address Line 1" %><br />
    <%= f.text_field :address_line_1, autocomplete: "on" %>
  </div>

  <% if @user.new_record? %>
    <%= f.submit "Create Account" %>
  <% else %>
    <%= f.submit "Update Account" %>
  <% end %>
  <%= link_to "Cancel", users_admin_index_path, class: 'button' %>
  </p>

<% end %>

app/views/users/edit.html.erb
<h1>Admin Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', user_path(@user) %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Users</h1>

<table>
  <thead>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Username</th>
    <th>Email</th>
    <th>Role</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td>
        <% if user.role_id == 1 %>
          <%= "Admin" %>
        <% elsif user.role_id == 2 %>
          <%= "Doctor" %>
        <% else %>
          <%= "Patient" %>
        <% end %>
      </td>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_users_admin_path(user) %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_users_admin_path %>

app/views/users/new.html.erb
<h1>Create New User</h1>

<%= render 'users/form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h2>My Profile</h2>
<div id="user_status">
  <% if user_signed_in? %>
    Welcome <%= current_user.username %>! Not you?
    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%#= link_to "Register", new_user_registration_path %>
    <%= link_to "Sign in", new_user_session_path %>.
  <% end %>
</div>

<%= link_to 'Edit Profile', edit_user_registration_path %>

<div>
  <hr>
  <br>
  <% if user_signed_in? %>
    <% if current_user.role_id == 1 %>
      <%= link_to('Add New User', new_user_path, class: "btn btn-success") %>
      <%= link_to('All Users', users_admin_index_path, class: "btn btn-success") %>
    <% end %>
  <br>
  <br> <%= "Name: " %> <%= current_user.first_name %> <%= current_user.last_name %>
  <br> <%= "Birth Date: " %> <%= current_user.dob %>
  <br> <%= "Gender: " %> <%= current_user.gender%>
  <br> <%= "Province: " %> <%= current_user.province %>
  <br> <%= "City or Village: " %> <%= current_user.city_village %>
  <br> <%= "Address Line 1: " %> <%= current_user.address_line_1 %>
  <br> <%= "Contact: " %> <%= current_user.contact %>
  <% end %>
  <br>
</div>